CREATE DATABASE IF NOT EXISTS dbapi;
USE dbapi;

CREATE USER 'newuser'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON dbapi.* TO 'newuser'@'%';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` INT NOT NULL UNIQUE AUTO_INCREMENT,
  `userName` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY(`id`)
);