version: "3.2"
services:
  php-apache:
    build: "./docker/php-apache/"
    depends_on:
      - mysql
    ports:
      - "4201:80"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: dbapi
      DB_PORT: 3306
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   
