CREATE DATABASE IF NOT EXISTS dbapi;
USE dbapi;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` INT NOT NULL UNIQUE AUTO_INCREMENT,
  `userName` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY(`id`)
);
